reddit:
  client_id: 
  client_secret: 
  user_agent: reddix-dev/0.1 (+https://github.com/ck-zhang/reddix)
  scopes:
  - identity
  - mysubreddits
  - read
  - vote
  - subscribe
  redirect_uri: http://127.0.0.1:65010/reddix/callback
ui:
  theme: default
media:
  cache_dir: /home/b0nz1cu5/.cache/reddix
  max_size_bytes: 524288000
  default_ttl: 6h
  workers: 2
player:
  video_command:
  - mpv
  - --fs
  - '%URL%'
  video_detach: true
